<a href="https://colab.research.google.com/github/ak7109162-wq/Numpy_Python-_Library_fullNotes/blob/main/Class1file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
ar = np.array([1,2,3,4,5,6])
ar

array([1, 2, 3, 4, 5, 6])

# New section

In [ ]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [ ]:
a = [1,2,3.5,"hello"]  # ye list hai kisi v data type ko accept kar lega
#yedi hum isko aaray me convert kare to
a

[1, 2, 3.5, 'hello']

Lets create a matrix using list

In [ ]:
a = np.array([1,2,3.5,"hello"])  # yaha error de raha hai dtype =<u32 jiska mtlb
# hai ki array same data type hona chahiye {yaha sab ko string me convert kar
#de raha hai}
a

array(['1', '2', '3.5', 'hello'], dtype='<U32')

Now lets see how matlix looks like using numpy arrays

In [ ]:
l = [[1,2,3],[4,5,6],[7,8,9]]  # create only one dimensional matrics
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l) # array likhne par l convert ho ja raha hai 2 dimensional mateics

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Arrange function
arr = np.arange(1,12,2)
arr

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(0,1,10)  # Same space dega
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.random.rand(5)  # ye random element provide karta hai {this is a concept of
# of noramlisation kyu ki value 0 and 1 ke beech aati ahi}

array([0.57392788, 0.42817515, 0.79748944, 0.06267196, 0.77530173])

In [ ]:
np.random.randn(10)  # this is concept of standardization kyu ki value lies
#between -3 and 3

array([ 0.35461633, -1.29165938,  2.25487551, -1.80927938,  0.03411142,
        1.36765092, -0.42496865,  0.02040482, -0.33749884, -0.52283949])

In [ ]:
np.random.randint(6) # ye 1 to 6 ke beech koi random integer generate kar dega
# but hum ek adhik random integer generate karana chahte hai to

1

In [ ]:
np.random.randint(10,20,10) # 10 aur 20 ke beech 10 random integer
# generate karana chahte hai

array([15, 16, 14, 15, 10, 18, 11, 17, 12, 14])

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape  # ye array ka shape bata ta hai ki kitna rows and column hai

(3, 3)

In [ ]:
arr.size # ye size bata ta hai ki kitna total element hai

9

In [ ]:
arr.dtype  # ye data type ko bata ta hai

dtype('int64')

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[6,7,8]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
arr.min()  # ye array ka minum element find kar deta hai


np.int64(1)

In [ ]:
arr.max()  # ye array ka maximum value bata ta hai

np.int64(8)

In [ ]:
arr.sum()  # ye sabhi element ka sum kar ke de dega

np.int64(42)

In [ ]:
np.sum(arr,axis = 0) # yaha row wise add kar raha hai kyu row wise add karne
# hetu axis 0 provide karte hai Ex--(1+4+6),(2+5+7),(3+6+8) aur column wise
# karne hetu axis = 1 provide karte hai

array([11, 14, 17])

In [ ]:
np.sum(arr,axis = 1) # column wise sum karne hetu axis me 1 provide karte hai

array([ 6, 15, 21])

In [ ]:
arr.mean()  # ye mean bata ta hai

np.float64(4.666666666666667)

In [ ]:
arr.std()

np.float64(2.2110831935702664)

In [ ]:
arr.argmax()  # ye maximum element ka index bata ta hai

np.int64(8)

In [ ]:
arr.argmin()  # ye minimum element ka index bata ta hai

np.int64(0)

In [ ]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr = arr.reshape(6,5)  # ye reshape 6 rows and 5 column me covert kar dega
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])