<a href="https://colab.research.google.com/github/ak7109162-wq/Numpy_Python-_Library_fullNotes/blob/main/class2file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [ ]:
import numpy as np

##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [ ]:
arr = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(arr)
#.shape
print(arr.shape)
#. ndim --> number of dimensional
print(arr.ndim)

#. size --> number of elements
print(arr.size)

#.dtypes --> data type inside your array
print(arr.dtype)


(3, 3)
2
9
int64


Now lets see the 2D indexing aswell

In [ ]:
arr = np.array ([10,20,30,40,50])
# 1D array indexing and sclicing = list
print(arr[3])
print(arr[-1])
print(arr[-3])

40
50
30


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# indexing
# arr [row ,column]
print(arr[1,1])
print(arr[1,2])

5
6


Now we can also do the slicing lets see the **slicing in 1D**

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

1D slicing was really easy now lets see the **slicing in 2D**

In [ ]:
arr[0:2,0:2] # rows from 0,1 and columns from 0,1

array([[1, 2],
       [4, 5]])

There is one more thing known as **Boolean indexing**

In [ ]:
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [ ]:
arr[1:3,1]

array([5, 8])

In [ ]:
arr[1:,1:2]

array([[5],
       [8]])

## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr > 5)  # give true and false
print(arr[arr > 5]) # give value which is more than 5

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [ ]:
# when we have to convert an 1D array into an 2D array we use
# .reshape(row,column)
import numpy as np
arr = np.arange(12)
reshaped = arr.reshape(6,2)
reshaped


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
# .flatten() will convert an 2D into an 1D array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
oneD = arr.flatten()
oneD

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
#1 Addition of the arrays
print(a+b)

#2. subtracting of the arrays
print(a-b)

#3. multiplication
print(a*b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]


In [ ]:
a = np.array([10,20,30,40])
print(a*5)  # multiply each element by 5

[ 50 100 150 200]


In [ ]:
A = np.array([[10,20,30],
              [40,50,60]])
B = np.array([10,20,30]) # add with both rows and column
print(A+B)

[[20 40 60]
 [50 70 90]]


In [ ]:
# Basic statistical operations perform
arr = np.array([4,78,21,34,100,56])
#1. sum
print(f"sum is : {arr.sum()}")

#2. Mean
print(f"Mean(Average) is : {arr.mean()}")

#3 Min
print(f"Min is : {arr.min()}")

#4.Max
print(f"Max is : {arr.max()}")

#5. standard deviation
print(f"standard deviation is : {arr.std()}")

#6. varience
print(f"varience is : {arr.var()}")

#7. median




sum is : 293
Mean(Average) is : 48.833333333333336
Min is : 4
Max is : 100
standard deviation is : 32.97684372741306
varience is : 1087.4722222222224


In [ ]:
data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(f"sum of all : {data.sum()}")
# axis = 0 --> columns
# axis = 1 --> rows
print(f"sum of columns : {np.sum(data,axis = 0)}")
print(f"aum of rows : {np.sum(data,axis = 1)}")


sum of all : 45
sum of columns : [12 15 18]
aum of rows : [ 6 15 24]
