<a href="https://colab.research.google.com/github/ak7109162-wq/Numpy_Python-_Library_fullNotes/blob/main/class4file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [ ]:
import numpy as np
matrix = np.arange(1,13).reshape(3,4)
matrix

# matrix [[Row0,col1],[row1,col2]]

print(matrix)
matrix[[0,1],[1,2]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([2, 7])

You can do this fancy indexing in 2D Matrix aswell

In [ ]:
matrix[[1,2],[0,2]]

array([ 5, 11])

##Conditional Selection
Find values based on conditions or replace them.

In [ ]:
arr = np.array([5,7,11,18,30])
#we will get the indices only which are
# greater than 10
np.where(arr > 10)

# array mai jaha bhi 10se choti values aa rahi hai
# waha 0 se replace ho jayegi.
print(np.where(arr > 10, arr,0))

[ 0  0 11 18 30]


##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [ ]:
arr2 = np.array([23,25,30,50,100,75,80])
# replace the value with 0 which are less than 55
print(np.where(arr2 > 55, arr2, 0))

[  0   0   0   0 100  75  80]


In [ ]:
# Aam zindagi
array = np.array([2,10,56,1,54])
print(np.sort(array))  # sorting the array

index = np.argsort(array)
print(index)  # show the index of sorted element

[ 1  2 10 54 56]
[3 0 1 4 2]


##Concatenation & Stacking

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate([a,b]))


[1 2 3 4 5 6]


Vertical & Horizontal Stacking

In [ ]:
# Matrix sort
matrix = np.array([[4,3,12],[14,10,15]])

#1. Row wise sort (axis =1)
np.sort(matrix, axis = 1)

#2. column wise sort(axis = 0)
np.sort(matrix, axis = 0)

#3. sort complete matrix
np.sort(matrix)

array([[ 3,  4, 12],
       [10, 14, 15]])

In [ ]:
A = np.array([[1,2],[4,5]])
B = np.array([[7,8],[10,11]])

# vertical stacking
print(np.vstack([A,B]))

# Horizontal stacking
print(np.hstack([A,B]))


[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]
[[ 1  2  7  8]
 [ 4  5 10 11]]
