<a href="https://colab.research.google.com/github/ak7109162-wq/Numpy_Python-_Library_fullNotes/blob/main/Class1file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Using NumPy**

Once you've installed NumPy you can import it as a library:

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
import numpy as np
a = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
matrix = np.array(a)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Lets create a matrix using list

In [ ]:
import numpy as np
# np.zeros() for 1D
np.zeros(4)

array([0., 0., 0., 0.])

Now lets see how matlix looks like using numpy arrays

In [ ]:
#np.zeros() for matrix
# rows and columns
np.zeros([3,4]) # rows

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [ ]:
np.ones(4)

In [ ]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full(5,7)

array([7, 7, 7, 7, 7])

In [ ]:
np.full([3,3],7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
#np.arange
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [ ]:
#np.eye() # identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#np.linspace() # start = 0 ,stop =1, value =5
np.linspace(0,1,5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
l = [10,20,30,40,50]
array = np.array(1)
print(array)
print(array.mean())

1
1.0


In [ ]:
#np.random.rand()  # rows , columns
np.random.rand(2,3)

array([[0.9835983 , 0.6288387 , 0.14166965],
       [0.30409603, 0.3649522 , 0.4879709 ]])

In [ ]:
#np.random.randint(start,stop,(rows,columns))
np.random.randint(1,20,(3,3))

""" randint --> 1 se 20 ke beech ki random values se matrixx create karega"""

array([[ 5,  8,  2],
       [18,  7, 16],
       [ 9, 16, 14]])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution