<a href="https://colab.research.google.com/github/ak7109162-wq/Numpy_Python-_Library_fullNotes/blob/main/numpy_final_assign_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Final NumPy Assignment
# Inputs khud se create karna hai



# Q1. Array Creation and Attributes

## Problem Statement
Create array [10,20,30,40,50] and print shape, ndim, size and dtype.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(f"shape of array : {arr.shape}")
print(f"Dimensional of array : {arr.ndim}")
print(f"size of array : {arr.size}")
print(f"Data type of array : {arr.dtype}")

shape of array : (5,)
Dimensional of array : 1
size of array : 5
Data type of array : int64



# Q2. Matrix Creation

## Problem Statement
Create a 3x3 NumPy matrix and print it.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]
                          ])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]



# Q3. Indexing Practice

## Problem Statement
Print first, third and last element from an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
arr = np.array([10,20,30,40,50])
print(f"first element : {arr[0]}")
print(f"third element : {arr[2]}")
print(f"last element : {arr[-1]}")

first element : 10
third element : 30
last element : 50



# Q4. Slicing Practice

## Problem Statement
Print elements from index 2 to 5.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
arr = np.array([10,20,30,40,50,60])
print(arr[2:5])

[30 40 50]



# Q5. Fancy Indexing

## Problem Statement
Print selected elements using fancy indexing.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
# Fancy index ka mtlb ek sath kai index ke element nikala jata hai
arr = np.array([10,20,30,40,50,60])
print(arr[[0,2,4]])
# ye 0 index ka element ,2 index ka element aur 4 index ka element print kar
# raha hai

[10 30 50]



# Q6. Conditional Selection

## Problem Statement
Print values greater than 15.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
arr = np.array([5,12,23,14,18,23,19,11])
print(arr[arr > 15])

[23 18 23 19]



# Q7. Broadcasting

## Problem Statement
Add 10 to every element of an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr+ 10)

[11 12 13 14 15]



# Q8. Aggregate Functions

## Problem Statement
Print sum, mean, max and min.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
arr = np.array([10,20,30,40,50,60])
print(f"sum of array : {arr.sum()}")
print(f"mean of array : {arr.mean()}")
print(f"maximum of array : {arr.max()}")
print(f"minimum of array : {arr.min()}")

sum of array : 210
mean of array : 35.0
maximum of array : 60
minimum of array : 10



# Q9. Sorting

## Problem Statement
Sort an unsorted NumPy array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
arr = np.array([8,5,6,9,18,15,13,22,19,10,6])
print(np.sort(arr))

[ 5  6  6  8  9 10 13 15 18 19 22]



# Q10. Concatenation and Stacking

## Problem Statement
Perform concatenate and vstack on two arrays.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(np.vstack((arr1,arr2)))  # vertical stack means ek ke upar ek rakhna
# Top to bottom

print(np.concatenate((arr1,arr2)))  # concatenate me dono array ko jor kar ek
# single array bana deta hai

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
